Fix invalid code
This code is invalid and breaks the Office build.

https://developercommunity.visualstudio.com/t/accepts-invalid-MSVC-accepts-attribute/10051607?space=62&scope=follow&sort=newest

D:\dbs\el\odm\Import\x64\debug\mso\x-none\x64\opensource_reactnative\x-none\include\Microsoft.ReactNative.Cxx\JSValueWriter.h(290,45): error: 'maybe_unused' attribute cannot be applied to types
  return [&args...](IJSValueWriter const &[[maybe_unused]] writer) noexcept { (WriteValue(writer, args), ...); };
                                            ^