Make JSValueReader.h compile with Clang [RFC] (#4481)
* Make JSValueReader.h compile with Clang [RFC]
I have spent quite some time on this but I can't make it compile as a static assert prevents compilation using Clang.

```
In file included from react-native-windows_MicrosoftReactNativeCxx_targetWindows#header-mode-symlink-tree-only,headers\NativeModules.h:8:
react-native-windows_MicrosoftReactNativeCxx_targetWindows#header-mode-symlink-tree-only,headers/JSValueReader.h:391:26: error: no member named 'ReadFrom' in 'std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, winrt::Microsoft::ReactNative::JSValue, std::less<void>, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, winrt::Microsoft::ReactNative::JSValue> > >'
  value = JSValueObject::ReadFrom(reader);
          ~~~~~~~~~~~~~~~^
react-native-windows_MicrosoftReactNativeCxx_targetWindows#header-mode-symlink-tree-only,headers/JSValueReader.h:395:25: error: no member named 'ReadFrom' in 'std::vector<winrt::Microsoft::ReactNative::JSValue, std::allocator<winrt::Microsoft::ReactNative::JSValue> >'
  value = JSValueArray::ReadFrom(reader);
          ~~~~~~~~~~~~~~^
react-native-windows_MicrosoftReactNativeCxx_targetWindows#header-mode-symlink-tree-only,headers/JSValueReader.h:156:5: error: static_assert failed "Unsupported char type"
    static_assert(false, "Unsupported char type");
```

The problem happens here > https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative.Cxx/JSValueReader.h#L156

But we only pass in ```char``` and ```wchar_t```  > https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative.Cxx/JSValueReader.h#L168-L192

I looked at https://docs.microsoft.com/en-us/cpp/build/reference/zc-wchar-t-wchar-t-is-native-type?view=vs-2019 but it did help me either.

Also tried to treat ```unsigned short as wchar_t```
https://docs.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp?view=vs-2019 ... no luck

The ```basic_string_convert``` is only used with ```char``` and ```wchar_t``` and the only arguments passed in are ```Int64_t``` and ```double```

* Change files

* Apply code-format

* Remove trailing zeros
https://stackoverflow.com/a/13709929