Changes needed to compile with clang (#8947)
* Changes needed to compile with clang

This adds a few additional changes needed to compile with clang.
- Additional struct GUIDs for winrt base types
- Avoiding the following clang error:
```
 error: qualified reference to 'duration' is a constructor name rather
 than a type in this context
```

* Change files